insert into brand(name) values ('Subaru');
insert into brand(name) values ('Chevrolet');
insert into brand(name) values ('Volkswagen');
insert into brand(name) values ('Ford');
insert into brand(name) values ('BYD (Build Your Dreams)');
insert into brand(name) values ('Kia');
insert into brand(name) values ('Renault');
insert into brand(name) values ('Toyota');
insert into brand(name) values ('Mazda');
insert into brand(name) values ('Peugeot');
insert into brand(name) values ('Nissan');
insert into brand(name) values ('Fiat');
insert into brand(name) values ('Hyundai');
insert into brand(name) values ('Honda');
insert into brand(name) values ('Mitsubishi');
insert into brand(name) values ('Suzuki');
insert into brand(name) values ('Jeep');
insert into brand(name) values ('Seat');
insert into brand(name) values ('Rover');
insert into brand(name) values ('Audi');
insert into brand(name) values ('Volvo');
insert into brand(name) values ('Mini');
insert into brand(name) values ('Lexus');
insert into brand(name) values ('Alfa Romeo');
insert into brand(name) values ('Mercedes Benz');
insert into brand(name) values ('Daihatsu');
insert into brand(name) values ('Cadillac');
insert into brand(name) values ('Isuzu');
insert into brand(name) values ('Daewoo');
insert into brand(name) values ('BMW');
insert into brand(name) values ('Dodge');
insert into brand(name) values ('Acura');
insert into brand(name) values ('Citroen');
insert into brand(name) values ('Chery');
insert into brand(name) values ('Rouser/Bajaj');
insert into brand(name) values ('Yamaha');
insert into brand(name) values ('Benelli');
insert into brand(name) values ('KTM');
insert into brand(name) values ('Kawasaki');
insert into brand(name) values ('Ducati');
insert into brand(name) values ('Lifan');
insert into brand(name) values ('Zanella');
insert into brand(name) values ('Harley-Davidson');
insert into brand(name) values ('Royal Enfield');
insert into brand(name) values ('Husqvarna');
insert into brand(name) values ('Gilera');
insert into brand(name) values ('Corven');
insert into brand(name) values ('Motomel');
